services:
  - type: web
    name: edtech-api
    runtime: docker
    repo: https://github.com/Akshit7887/-edtech-web.git
    rootDir: edtech-web/EdTechApi
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health/live
    numInstances: 1
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: NEON_CONNECTION_STRING
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GOOGLE_FRONTEND_REDIRECT
        sync: false
      - key: REDIS_CONNECTION_STRING
        sync: false
